FROM tvm-host

USER root

# Make apt non-interactive to keep installation from being blocked
ENV DEBIAN_FRONTEND=noninteractive
ENV LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu/:${LD_LIBRARY_PATH}"

# install sudo and don't fail
RUN yes O | apt install -y sudo

# install OS package dependencies
ADD ./docker/dependencies/apt.txt apt.txt
RUN grep -vE '^#' apt.txt | xargs apt install -y

# install python dependences
ADD ./docker/dependencies/pip.txt pip.txt
RUN pip3 install -r pip.txt
